language: python
python:
    - 3.5
    - 3.6

os: linux

install:
    - "pip install -r requirements.txt"
    - "pip install -r req-dev.txt"

script:
    - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then make coverage'

after_success: coveralls
