language: python
matrix:
    include:
        - os: linux
          python: 3.3
        - os: linux
          python: 3.4
        - os: linux
          python: 3.5
        - os: osx
          python: 3.4

install:
    - "pip install -r requirements.txt"
    - "pip install -r req-dev.txt"

script: make coverage

after_success: coveralls
